name: Deploy Laravel Sail (Remote)
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue de web xunga
        uses: appleboy/ssh-action@v1.0.0
        
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            set -e
            cd /var/www/html/webda
            git config --global --add safe.directory /var/www/html/webda
            git pull
            